import {
  Calendar,
  CalendarRange,
  Image as ImageIcon,
  Info,
  Layout,
  MapPin,
  Megaphone,
  Ticket,
  Users,
} from "lucide-react";
import type { DashboardModuleConfig, DashboardModuleField } from "../dashboard/dashboardTypes";
import { countByValue } from "../dashboard/dashboardTypes";

const basicFields: DashboardModuleField[] = [
  {
    key: "title",
    label: "Event Name",
    type: "text",
    placeholder: "e.g. ICASD 2026 - International Research Conference",
    required: true,
    span: 2,
  },
  {
    key: "type",
    label: "Event Type",
    type: "select",
    options: ["Conference", "Webinar", "Workshop", "Meetup", "Forum", "Summit", "Award"],
    placeholder: "Select event type",
    required: true,
  },
  {
    key: "category",
    label: "Category",
    type: "select",
    options: ["Education", "Technology", "Health", "Environment", "Social", "Business"],
    placeholder: "Select category",
    required: true,
  },
  {
    key: "shortDescription",
    label: "Short Description",
    type: "text",
    placeholder: "Brief summary of the event",
    required: true,
    span: 2,
  },
  {
    key: "description",
    label: "Detailed Description",
    type: "textarea",
    placeholder: "Full event details, goals, and information",
    required: true,
    span: 2,
  },
  {
    key: "tags",
    label: "Tags (comma-separated)",
    type: "text",
    placeholder: "Sustainability, Innovation, Research",
    required: false,
  },
  {
    key: "organizer",
    label: "Organizer Name / Organization",
    type: "text",
    placeholder: "e.g. Acadivate Global",
    required: true,
  },
  {
    key: "status",
    label: "Event Status",
    type: "select",
    options: ["Draft", "Published", "Scheduled", "Archived"],
    placeholder: "Select publication status",
    required: true,
  },
  {
    key: "relatedAward",
    label: "Related Award",
    type: "select",
    sourceModule: "awards",
    placeholder: "Link this event to an award",
    required: false,
    span: 2,
  },
];

const dateTimeFields: DashboardModuleField[] = [
  {
    key: "startDate",
    label: "Start Date",
    type: "date",
    placeholder: "Select start date",
    required: true,
  },
  {
    key: "startTime",
    label: "Start Time",
    type: "time",
    placeholder: "Select start time",
    required: true,
  },
  {
    key: "endDate",
    label: "End Date",
    type: "date",
    placeholder: "Select end date",
    required: true,
  },
  {
    key: "endTime",
    label: "End Time",
    type: "time",
    placeholder: "Select end time",
    required: true,
  },
  {
    key: "timeZone",
    label: "Time Zone",
    type: "select",
    options: ["UTC", "GMT", "PST", "EST", "IST", "SGT"],
    placeholder: "Select time zone",
    required: true,
  },
  {
    key: "registrationDeadline",
    label: "Registration Deadline",
    type: "date",
    placeholder: "Select deadline",
    required: true,
  },
  {
    key: "isRecurring",
    label: "Recurring Event",
    type: "checkbox",
    placeholder: "This is a recurring event",
    required: false,
  },
  {
    key: "frequency",
    label: "Frequency",
    type: "select",
    options: ["Daily", "Weekly", "Monthly", "Yearly"],
    placeholder: "Select frequency",
    required: false,
    showIf: { key: "isRecurring", value: true },
  },
];

const locationFields: DashboardModuleField[] = [
  {
    key: "locationType",
    label: "Location Type",
    type: "select",
    options: ["Offline", "Online"],
    placeholder: "Select location type",
    required: true,
    span: 2,
  },
  {
    key: "venueName",
    label: "Venue Name",
    type: "text",
    placeholder: "e.g. Grand Convention Center",
    required: false,
    showIf: { key: "locationType", value: "Offline" },
  },
  {
    key: "address",
    label: "Address",
    type: "text",
    placeholder: "Street address",
    required: false,
    span: 2,
    showIf: { key: "locationType", value: "Offline" },
  },
  {
    key: "city",
    label: "City",
    type: "text",
    placeholder: "City",
    required: false,
    showIf: { key: "locationType", value: "Offline" },
  },
  {
    key: "country",
    label: "Country",
    type: "text",
    placeholder: "Country",
    required: false,
    showIf: { key: "locationType", value: "Offline" },
  },
  {
    key: "googleMapsLink",
    label: "Google Maps link / coordinates",
    type: "text",
    placeholder: "https://maps.google.com/...",
    required: false,
    span: 2,
    showIf: { key: "locationType", value: "Offline" },
  },
  {
    key: "onlinePlatform",
    label: "Platform (Online)",
    type: "select",
    options: ["Zoom", "Google Meet", "Microsoft Teams", "Webex", "YouTube Live"],
    placeholder: "Select platform",
    required: false,
    showIf: { key: "locationType", value: "Online" },
  },
  {
    key: "meetingLink",
    label: "Meeting Link",
    type: "text",
    placeholder: "https://zoom.us/j/...",
    required: false,
    showIf: { key: "locationType", value: "Online" },
  },
  {
    key: "accessInstructions",
    label: "Access Instructions",
    type: "textarea",
    placeholder: "How to join the event",
    required: false,
    span: 2,
    showIf: { key: "locationType", value: "Online" },
  },
];

const ticketFields: DashboardModuleField[] = [
  {
    key: "enableTickets",
    label: "Enable Tickets & Pricing",
    type: "checkbox",
    placeholder: "This event has ticket options",
    required: false,
    span: 2,
  },
  {
    key: "ticketType",
    label: "Ticket Type",
    type: "select",
    options: ["Free", "Paid", "Donation"],
    placeholder: "Select ticket type",
    required: true,
    showIf: { key: "enableTickets", value: true },
  },
  {
    key: "price",
    label: "Price",
    type: "text",
    placeholder: "e.g. $99.00",
    required: false,
    showIf: { key: "enableTickets", value: true },
  },
  {
    key: "capacity",
    label: "Quantity / Capacity",
    type: "number",
    placeholder: "Max tickets available",
    required: true,
    showIf: { key: "enableTickets", value: true },
  },
  {
    key: "ticketName",
    label: "Ticket Name",
    type: "text",
    placeholder: "e.g. Early Bird, VIP, Regular",
    required: true,
    showIf: { key: "enableTickets", value: true },
  },
  {
    key: "saleStartDate",
    label: "Sale Start Date",
    type: "date",
    placeholder: "Start date",
    required: false,
    showIf: { key: "enableTickets", value: true },
  },
  {
    key: "saleEndDate",
    label: "Sale End Date",
    type: "date",
    placeholder: "End date",
    required: false,
    showIf: { key: "enableTickets", value: true },
  },
  {
    key: "refundPolicy",
    label: "Refund Policy",
    type: "textarea",
    placeholder: "Describe refund rules",
    required: false,
    span: 2,
    showIf: { key: "enableTickets", value: true },
  },
];

const attendeeFields: DashboardModuleField[] = [
  {
    key: "customRegistrationForm",
    label: "Form Builder",
    type: "repeater",
    placeholder: "Build your registration form",
    required: false,
    span: 2,
    subFields: [
      {
        key: "fieldLabel",
        label: "Field Label",
        type: "text",
        placeholder: "e.g. Job Title",
      },
      {
        key: "fieldType",
        label: "Field Type",
        type: "select",
        options: ["Text", "Number", "Select", "Checkbox", "Textarea"],
        placeholder: "Select type",
      },
      {
        key: "required",
        label: "Required",
        type: "checkbox",
        placeholder: "Is this field mandatory?",
      },
    ],
  },
  {
    key: "maxAttendees",
    label: "Max Attendees",
    type: "number",
    placeholder: "Overall event capacity",
    required: false,
  },
  {
    key: "approvalRequired",
    label: "Approval Required",
    type: "select",
    options: ["Yes", "No"],
    placeholder: "Do you need to approve registrations?",
    required: true,
  },
];

const detailFields: DashboardModuleField[] = [
  {
    key: "agenda",
    label: "Agenda / Schedule",
    type: "repeater",
    placeholder: "Manage event schedule",
    required: false,
    span: 2,
    subFields: [
      {
        key: "time",
        label: "Time Slot",
        type: "text",
        placeholder: "09:00 AM - 10:00 AM",
      },
      {
        key: "activity",
        label: "Activity",
        type: "text",
        placeholder: "Opening Ceremony",
      },
      {
        key: "speaker",
        label: "Speaker / Moderator",
        type: "text",
        placeholder: "Name of the person",
      },
    ],
  },
  {
    key: "speakers",
    label: "Speakers",
    type: "repeater",
    placeholder: "Manage speakers",
    required: false,
    span: 2,
    subFields: [
      { key: "name", label: "Name", type: "text", placeholder: "Full Name" },
      { key: "role", label: "Role", type: "text", placeholder: "e.g. CEO, Google" },
      { key: "bio", label: "Bio", type: "textarea", placeholder: "Short bio" },
      { key: "photo", label: "Photo URL", type: "text", placeholder: "Image URL" },
    ],
  },
  {
    key: "faqs",
    label: "FAQs",
    type: "repeater",
    placeholder: "Manage frequently asked questions",
    required: false,
    span: 2,
    subFields: [
      { key: "question", label: "Question", type: "text", placeholder: "The question" },
      { key: "answer", label: "Answer", type: "textarea", placeholder: "The answer" },
    ],
  },
  {
    key: "termsAndConditions",
    label: "Terms & Conditions",
    type: "repeater",
    placeholder: "Manage terms and conditions",
    required: false,
    span: 2,
    subFields: [
      { key: "title", label: "Section Title", type: "text", placeholder: "e.g. Cancellation Policy" },
      { key: "content", label: "Content", type: "textarea", placeholder: "The details" },
    ],
  },
];

const mediaFields: DashboardModuleField[] = [
  {
    key: "bannerImage",
    label: "Event Banner Image",
    type: "file",
    placeholder: "High resolution wide banner",
    accept: "image/*",
    span: 2,
  },
  {
    key: "thumbnailImage",
    label: "Thumbnail Image",
    type: "file",
    placeholder: "Square or 4:3 preview image",
    accept: "image/*",
  },
  {
    key: "brochure",
    label: "Event Brochure",
    type: "file",
    placeholder: "Upload event brochure (PDF)",
    accept: "application/pdf",
    span: 2,
  },
  {
    key: "gallery",
    label: "Gallery Images",
    type: "file",
    placeholder: "Upload multiple event photos",
    accept: "image/*",
    multiple: true,
  },
  {
    key: "theme",
    label: "Theme / Branding",
    type: "textarea",
    placeholder: "Primary Color, Fonts, Style Guide",
    required: false,
    span: 2,
  },
];

const marketingFields: DashboardModuleField[] = [
  {
    key: "slug",
    label: "Slug / URL",
    type: "text",
    placeholder: "icasd-2026",
    required: true,
  },
  {
    key: "metaTitle",
    label: "Meta Title",
    type: "text",
    placeholder: "SEO optimized title",
    required: false,
  },
  {
    key: "metaDescription",
    label: "Meta Description",
    type: "textarea",
    placeholder: "SEO meta description",
    required: false,
    span: 2,
  },
  {
    key: "socialSharingImage",
    label: "Social Sharing Image",
    type: "file",
    placeholder: "Image for OG tags",
    accept: "image/*",
    span: 2,
  },
  {
    key: "seoKeywords",
    label: "Keywords / Tags",
    type: "text",
    placeholder: "Separated by commas",
    required: false,
    span: 2,
  },
];

export const eventsModule: DashboardModuleConfig = {
  id: "events",
  title: "Events",
  subtitle:
    "Create, edit, publish, and archive conferences, workshops, and featured events.",
  intro:
    "Keep the public event feed, featured cards, and admin records synchronized from one page.",
  route: "/dashboard/events",
  actionLabel: "Add Event",
  searchPlaceholder: "Search events, dates, and venues...",
  accent: "primary",
  icon: CalendarRange,
  fields: [
    ...basicFields,
    ...dateTimeFields,
    ...locationFields,
    ...ticketFields,
    ...attendeeFields,
    ...detailFields,
    ...mediaFields,
    ...marketingFields,
  ],
  sections: [
    {
      id: "basic",
      title: "Basic Information",
      subtitle: "This is the core of your event.",
      icon: Info,
      fields: basicFields,
    },
    {
      id: "datetime",
      title: "Date & Time",
      subtitle: "Keep all scheduling here.",
      icon: Calendar,
      fields: dateTimeFields,
    },
    {
      id: "location",
      title: "Location / Venue",
      subtitle: "Make it dynamic based on type.",
      icon: MapPin,
      fields: locationFields,
    },
    {
      id: "tickets",
      title: "Tickets & Pricing",
      subtitle: "Even free events should have this.",
      icon: Ticket,
      fields: ticketFields,
    },
    {
      id: "attendees",
      title: "Attendees & Registration",
      subtitle: "This is where your form builder mindset kicks in.",
      icon: Users,
      fields: attendeeFields,
    },
    {
      id: "details",
      title: "Event Details / Content",
      subtitle: "More structured content.",
      icon: Layout,
      fields: detailFields,
    },
    {
      id: "media",
      title: "Media & Branding",
      subtitle: "Important for UI/UX.",
      icon: ImageIcon,
      fields: mediaFields,
    },
    {
      id: "marketing",
      title: "Marketing & SEO",
      subtitle: "Useful if events are public.",
      icon: Megaphone,
      fields: marketingFields,
    },
  ],
  columns: [
    { key: "title", label: "Title" },
    { key: "startDate", label: "Date" },
    { key: "venueName", label: "Location" },
    { key: "type", label: "Type" },
    { key: "status", label: "Status" },
  ],
  tableTemplateColumns:
    "minmax(0, 1.45fr) minmax(0, 0.9fr) minmax(0, 1.15fr) minmax(0, 0.8fr) minmax(0, 0.85fr)",
  initialRows: [
    {
      id: "660000000000000000000001",
      values: {
        title: "ICASD 2026 - International Research Conference",
        slug: "icasd-2026",
        type: "Conference",
        startDate: "2026-05-21 09:00 AM",
        venueName: "Kuala Lumpur, Malaysia",
        status: "Published",
      },
    },
    {
      id: "660000000000000000000002",
      values: {
        title: "ICGSD 2025 - Global Academic Conference",
        slug: "icgsd-2025",
        type: "Conference",
        startDate: "2025-07-22 10:00 AM",
        venueName: "Dubai, UAE",
        status: "Scheduled",
      },
    },
  ],
  statusToneMap: {
    Draft: "warning",
    Scheduled: "neutral",
    Published: "success",
    Archived: "danger",
  },
  buildSummary: (rows) => [
    { label: "Total events", value: String(rows.length), tone: "neutral" },
    {
      label: "Published",
      value: String(countByValue(rows, "status", "Published")),
      tone: "success",
    },
    {
      label: "Scheduled",
      value: String(countByValue(rows, "status", "Scheduled")),
      tone: "warning",
    },
  ],
};
